import { createFileRoute } from "@tanstack/react-router";
import { LegalPage, Section, Bullets } from "../components/LegalPage";

export const Route = createFileRoute("/terms")({
  component: Terms,
  head: () => ({
    meta: [
      { title: "Terms of Service — Alphonso" },
      {
        name: "description",
        content:
          "The rules for using Alphonso: your account, acceptable use, AI features and liability.",
      },
      { property: "og:title", content: "Terms of Service — Alphonso" },
      { property: "og:description", content: "The agreement between you and Alphonso." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary" },
    ],
  }),
});

const CONTACT = "support@alphonsoecosystem.app";

function Terms() {
  return (
    <LegalPage title="Terms of Service" updated="25 September 2026">
      <Section heading="Agreement">
        <p>
          By creating an account or using Alphonso you agree to these terms. If you do not agree,
          please do not use the app.
        </p>
      </Section>

      <Section heading="Your account">
        <Bullets
          items={[
            "You must be at least 13 years old, or 16 where local law requires.",
            "Keep your password secure; you are responsible for activity on your account.",
            "One account per person. Accounts are personal and not transferable.",
          ]}
        />
      </Section>

      <Section heading="Acceptable use">
        <Bullets
          items={[
            "Do not harass, impersonate or abuse other learners, including through your display name.",
            "Do not attempt to manipulate XP, streaks or league standings by automated or fraudulent means.",
            "Do not scrape, resell or redistribute lesson content, or attempt to bypass usage limits.",
            "Do not use the AI tutor to generate unlawful, hateful or sexually explicit content.",
          ]}
        />
        <p>We may suspend or remove accounts that break these rules.</p>
      </Section>

      <Section heading="AI features">
        <p>
          Conversation practice, pronunciation feedback and speech features are generated by AI
          models — NVIDIA for the AI tutor's conversation responses, Deepgram for speech-to-text and
          text-to-speech. They can be wrong or inappropriate. Treat output as practice material, not
          professional or certified language instruction. Fair-use daily limits apply per account.
        </p>
      </Section>

      <Section heading="Content and ownership">
        <p>
          Lessons, questions, artwork and the app itself belong to us or our licensors. Text you
          write remains yours; you grant us the licence needed to store and process it so the app
          can work.
        </p>
      </Section>

      <Section heading="Availability">
        <p>
          The service is provided "as is". We do not guarantee uninterrupted availability, that
          content is error-free, or that any particular learning outcome will be achieved.
        </p>
      </Section>

      <Section heading="Liability">
        <p>
          To the extent permitted by law, we are not liable for indirect or consequential loss.
          Nothing here limits liability that cannot be limited by law, including for death or
          personal injury caused by negligence.
        </p>
      </Section>

      <Section heading="Ending the agreement">
        <p>
          You can delete your account at any time from Profile → Your data. We may terminate access
          for serious or repeated breaches of these terms.
        </p>
      </Section>

      <Section heading="Contact">
        <p>Questions about these terms: {CONTACT}.</p>
      </Section>
    </LegalPage>
  );
}
