import type { VocabImageRecord } from "./types";

const FIELDS = [
  "url",
  "alt",
  "credit",
  "source",
  "sourcePageUrl",
  "license",
  "reviewedBy",
  "reviewedAt",
] as const;

const HEADER = `// GENERATED by scripts/write-vocab-images.ts. Do not edit by hand.
// Vocab term -> self-hosted, visually reviewed stock photo (App Store
// remediation W1). Keyed by lowercased term so deriveVocab() in vocab.ts and
// question.imageKey can attach an image to any matching vocab item. Every entry
// is checked by src/data/vocab-images.guard.test.ts and covered by the owner
// sign-off in scripts/vocab-images/signoff.json. Pipeline: LESSON_ASSETS.md.`;

export function renderVocabImagesModule(images: Record<string, VocabImageRecord>): string {
  const keys = Object.keys(images).sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
  const body = keys
    .map((key) => {
      const fields = FIELDS.map((f) => `    ${f}: ${JSON.stringify(images[key][f])},`).join("\n");
      return `  ${JSON.stringify(key)}: {\n${fields}\n  },`;
    })
    .join("\n");
  return `${HEADER}
import type { VocabImageRecord } from "../lib/vocab-images/types";

export type VocabImage = VocabImageRecord;

export const VOCAB_IMAGES: Record<string, VocabImage> = {
${body}
};
`;
}
