import { describe, expect, it } from "vitest";
import { renderVocabImagesModule } from "./render";
import { LICENSE_FOR_SOURCE, type VocabImageRecord } from "./types";

const img = (alt: string): VocabImageRecord => ({
  url: "https://qhcjpfbxfcltjbiuknyt.supabase.co/storage/v1/object/public/vocab-images/en/x.jpg?v=0123abcd",
  alt,
  credit: "C",
  source: "pexels",
  sourcePageUrl: "https://www.pexels.com/photo/x-1/",
  license: LICENSE_FOR_SOURCE.pexels,
  reviewedBy: "agent:a",
  reviewedAt: "2026-10-08",
});

describe("renderVocabImagesModule", () => {
  it("is deterministic and sorted by key", () => {
    const a = renderVocabImagesModule({ zebra: img("Z"), apple: img("A") });
    expect(renderVocabImagesModule({ apple: img("A"), zebra: img("Z") })).toBe(a);
    expect(a.indexOf('"apple": {')).toBeLessThan(a.indexOf('"zebra": {'));
  });

  it("escapes quotes and backslashes into valid string literals", () => {
    const out = renderVocabImagesModule({ 'say "hi"': img('A "quoted" \\ alt') });
    expect(out).toContain('"say \\"hi\\"": {');
    expect(out).toContain('alt: "A \\"quoted\\" \\\\ alt",');
  });

  it("round-trips: the object literal evaluates back to the input", () => {
    const input = { apple: img("A red apple."), "l'école": img("A school building.") };
    const out = renderVocabImagesModule(input);
    const literal = out.slice(out.indexOf("= {") + 2, out.lastIndexOf("};") + 1);
    expect(new Function(`return (${literal});`)()).toEqual(input);
  });

  it("marks the file as generated and re-exports the record type", () => {
    const out = renderVocabImagesModule({ apple: img("A") });
    expect(out.startsWith("// GENERATED by scripts/write-vocab-images.ts")).toBe(true);
    expect(out).toContain("export type VocabImage = VocabImageRecord;");
  });
});
