/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoldersRouteImport } from './routes/folders'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as FolderIdRouteImport } from './routes/folder.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersRoute = FoldersRouteImport.update({
  id: '/folders',
  path: '/folders',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const FolderIdRoute = FolderIdRouteImport.update({
  id: '/folder/$id',
  path: '/folder/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/folders': typeof FoldersRoute
  '/reports': typeof ReportsRoute
  '/signin': typeof SigninRoute
  '/folder/$id': typeof FolderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/folders': typeof FoldersRoute
  '/reports': typeof ReportsRoute
  '/signin': typeof SigninRoute
  '/folder/$id': typeof FolderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/folders': typeof FoldersRoute
  '/reports': typeof ReportsRoute
  '/signin': typeof SigninRoute
  '/folder/$id': typeof FolderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/folders' | '/reports' | '/signin' | '/folder/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/folders' | '/reports' | '/signin' | '/folder/$id'
  id: '__root__' | '/' | '/folders' | '/reports' | '/signin' | '/folder/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FoldersRoute: typeof FoldersRoute
  ReportsRoute: typeof ReportsRoute
  SigninRoute: typeof SigninRoute
  FolderIdRoute: typeof FolderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders': {
      id: '/folders'
      path: '/folders'
      fullPath: '/folders'
      preLoaderRoute: typeof FoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folder/$id': {
      id: '/folder/$id'
      path: '/folder/$id'
      fullPath: '/folder/$id'
      preLoaderRoute: typeof FolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FoldersRoute: FoldersRoute,
  ReportsRoute: ReportsRoute,
  SigninRoute: SigninRoute,
  FolderIdRoute: FolderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
