/**
 * Generates the phase 1 audit log skeleton: one row per pack, per
 * hand-written unit, and for the placement pool. Coverage is proved by
 * enumeration -- every row must end the audit with a verdict, including
 * "no issues found".
 *
 * Usage: bun run scripts/init-audit-log.ts
 */
import fs from "node:fs";
import path from "node:path";
import { BANK } from "../src/data/lesson-bank";
import { getCourse } from "../src/data/courses";
import { PLACEMENT_QUESTIONS } from "../src/data/placement";

const allPacks = Object.values(BANK).flat();

const packRows = allPacks.map(
  (p) =>
    `| \`${p.id}\` | pack | ${p.title} | ${p.data.split("\n").filter((l) => l.trim()).length} | ☐ | |`,
);

const generatedPackIds = new Set(allPacks.map((p) => p.id));
const handWritten = getCourse("en")
  .curriculum.filter((u) => ![...generatedPackIds].some((id) => u.id.startsWith(id)))
  .map(
    (u) =>
      `| \`${u.id}\` | hand-written unit | ${u.title} | ${u.lessons.reduce((n, l) => n + l.questions.length, 0)} | ☐ | |`,
  );

const placementRow = `| \`placement\` | placement pool | Placement test | ${PLACEMENT_QUESTIONS.length} | ☐ | |`;

const body = `# English Content Audit Log (Phase 1)

> Generated by \`scripts/init-audit-log.ts\`. Every row must end with a
> verdict before phase 1 can be called done -- including "no issues
> found". Coverage is proved by enumeration, not sampling.
>
> Spec: \`docs/superpowers/specs/2026-09-23-english-content-overhaul-design.md\`

## Coverage

| Id | Kind | Title | Questions | Audited | Findings |
|---|---|---|---|---|---|
${[...packRows, ...handWritten, placementRow].join("\n")}

## Findings detail

_One section per finding: what was wrong, which checklist item it violates,
the exact edit applied (or "deferred: structural" / "deferred: re-level")._

## Deferred structural changes

_Line add/remove proposals and pack re-leveling proposals. Each needs an
explicit applied/declined decision before phase 1 exits._
`;

const out = path.resolve(import.meta.dirname, "../docs/superpowers/english-content-audit-log.md");
fs.writeFileSync(out, body);
console.log(`Wrote ${out}`);
console.log(`Rows: ${packRows.length} packs, ${handWritten.length} hand-written units, 1 placement`);
